"""Step 11: generate controlled noisy/distorted versions of every clean
audio file (white noise mild/medium/strong, speed up/down, pitch up/down).
Noisy files are generated by code from the clean audio, mirroring the
dataset_clean/toneX/ structure under dataset_noisy/<condition>/toneX/."""
import os
import sys
import numpy as np
import pandas as pd
import soundfile as sf

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src"))
from audio_utils import load_fixed, apply_condition, SR, NOISE_CONDITIONS

RESULTS = os.path.join(PROJECT_ROOT, "results")
DATASET_NOISY = os.path.join(PROJECT_ROOT, "dataset_noisy")

np.random.seed(42)

meta = pd.read_csv(os.path.join(RESULTS, "metadata_clean.csv"))

rows = []
for condition in NOISE_CONDITIONS:
    for _, row in meta.iterrows():
        clean_path = os.path.join(PROJECT_ROOT, row["filepath"])
        y = load_fixed(clean_path)
        y_noisy = apply_condition(y, SR, condition)

        out_dir = os.path.join(DATASET_NOISY, condition, f"tone{row['tone']}")
        os.makedirs(out_dir, exist_ok=True)
        fname = f"{row['syllable']}_tone{row['tone']}_{row['voice']}.wav"
        out_path = os.path.join(out_dir, fname)
        sf.write(out_path, y_noisy, SR)

        rows.append({
            "filepath": os.path.relpath(out_path, PROJECT_ROOT).replace("\\", "/"),
            "tone": row["tone"],
            "syllable": row["syllable"],
            "voice": row["voice"],
            "condition": condition,
            "split": row["split"],  # inherit split from the source clean file
        })
    print(f"Generated condition: {condition} ({len(meta)} files)")

noisy_meta = pd.DataFrame(rows)
noisy_meta.to_csv(os.path.join(RESULTS, "metadata_noisy.csv"), index=False)
print("\nTotal noisy files:", len(noisy_meta))
print(noisy_meta["condition"].value_counts())
print("Saved:", os.path.join(RESULTS, "metadata_noisy.csv"))
